version: '3'
services:
  app:
    build:
      context: ./packages/backend
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    environment:
      - APP_ENV=docker

  mongodb:
    container_name: mongodb
    image: mongo:4.0
    ports:
      - 27017:27017
